### ISSUE TITLE
[Issue] Tier rates reading incorrectly

### ISSUE THREAD

**Issue by firstof9** [firstof9/ha-openei#28]
I updated and now the rate is at the highest tier even though I'm just realizing I think it ought to be on tier 1 right now with the value of the 1 month energy sensor (6.8 kWh /day * 30 = 204)  I'm at 113 kWh so I'm below the baseline right now so in 92 kWh it should switch to tier 2 then once it reaches 400% of that baseline value it should go to tier 3.

_Originally posted by @coleya in https://github.com/firstof9/ha-openei/issues/17#issuecomment-915589468_

**Comment by firstof9** [comment]
While this is true, the way the data is presented it's looking for a `per day` sensor.
Do you have a daily meter setup as well as monthly?

**Comment by coleya** [comment]
I do have a daily meter I tried to change to it but it seems #23 might not have been completely fixed. I'll reinstall and see if it works with the daily one but I'm not sure that's going to produce correct results for a price total.

**Comment by coleya** [comment]
okay so I changed to the daily sensor and unsurprisingly it now is at the lowest tier but I'm still not sure that this accurately reflects the rate since it is done at the end of the month with the total so I might never be charged the highest energy rate but if I use tons of energy on one day (laundry day perhaps) it will show that I'm being charged a rate that I never will actually be charged.

**Comment by firstof9** [comment]
So this is how it's listed in the API:
```json
            "energyratestructure": [
                [
                    {
                        "max": 6.8,
                        "rate": 0.25902,
                        "unit": "kWh daily"
                    },
                    {
                        "max": 27.2,
                        "rate": 0.32596,
                        "unit": "kWh daily"
                    },
                    {
                        "rate": 0.40745,
                        "unit": "kWh daily"
                    }
                ],
                [
                    {
                        "max": 8.2,
                        "rate": 0.25902,
                        "unit": "kWh daily"
                    },
                    {
                        "max": 32.8,
                        "rate": 0.32596,
                        "unit": "kWh daily"
                    },
                    {
                        "rate": 0.40745,
                        "unit": "kWh daily"
                    }
                ]
            ],
```

Just so I understand these are not actually measured daily but an over a 30 day average right?

**Comment by coleya** [comment]
It's calculated at the end of every month and the first 6.8 kWh * number of days in that month are charged at 0.25902 $ / kWh (more now but I already summited the updated tariff to the database admin so that will hopefully not be true for long)and the next 3 * 6.8 kWh * number of days in that month are charged at 0.32596 $ / kWh. Everything above that is charged at 0.40745 $ / kWh. The other rates are for the winter which is October 1 through May 31. The seasons are kinda complicated so I'm just going to quote the [tariff PDF](https://www.pge.com/tariffs/assets/pdf/tariffbook/ELEC_SCHEDS_E-1.pdf) "The summer season is June 1 through September 30 and the winter season is October 1 through May 31. Bills that include June 1 and October 1 seasonal changeover dates will be calculated by multiplying the applicable daily baseline quantity for each season by the number of days in each season for the billing period."

**Comment by firstof9** [comment]
Ok, I'll see what I can come up with here.

**Comment by coleya** [comment]
At 4 PDT the current price sensor updated to the tier 2 price I think that's the first time it checked the price since the 1 day energy sensor crossed 6.8 since it was at 6.72 at 3 so it looks like it is currently working as you intended. A few other things to note from that tariff document is that there is a per day cost of $0.33260 and then there is a "credit" which could be a negative or positive value on the bill, I'm not sure that reads "California Climate Credit (per household, per semi-annual payment occurring in the April and October bill cycles) ($17.20)".

**Comment by firstof9** [comment]
That kind of data isn't exposed via the API.

**Comment by coleya** [comment]
Oh well, I assumed the day would be there since there seems to be a section for fixed charges on openei.org [here](https://openei.org/apps/USURDB/rate/view/60e4c63a5457a3a91679e0f2#4__Fixed_Charges) even though the number doesn't seem correct.

**Comment by firstof9** [comment]
So for the `number of days in that month are charged` do you think an average of 29 would suffice for calculations?
The goal isn't to be exact but at least in the ball park.

**Comment by firstof9** [comment]
Would you be able to test the latest PR locally and feed it your monthly sensor?
It _should_ report the correct rate under a new sensor.

**Comment by coleya** [comment]
It would be nice to use something like the calendar python module to get the actual number of days in the particular month (to automatically account for February) but I understand if that's too complicated so the average number of days in a month is a bit under 30 and a half.

**Comment by firstof9** [comment]
Right I under stand that, but billing cycles, they fluctuate from something like 28-32 days, 29 seems like a happy median.

**Comment by coleya** [comment]
I looked for any new betas or versions and all I saw was 0.1.3 which I installed and when I switched to the monthly sensor it just went up to the tier 3 rate which it shouldn't be at yet. As to the number of days to choose I'm really not sure but my billing period seems to fluctuate between 29-33 days with most months being 30 days. Its a shame they don't expose that fixed charges section from their website on their API, this could be quite accurate if they did, as is it will be a nice estimate and a reminder for when the rate has increased.

**Comment by firstof9** [comment]
I've released it as a beta.

**Comment by coleya** [comment]
I've installed the beta and switched the sensor and it went up to the tier 3 rate but this time I thought I'd double check the number and it seems like the integration that monitors the energy has two days of incorrect energy usage data that say I used over 1000 kWh but this incorrect data is only on the daily sensor for sep 2-3 the monthly sensor is still only a bit over 130 so I don't think it is the cause of the bug just thought I'd mention it just in case.

**Comment by firstof9** [comment]
So with your monthly sensor is it providing the proper rate under the new sensor that was created?

**Comment by coleya** [comment]
That sensor currently reads out the tier 1 rate which I believe is what it should be right now. Since the current rate sensor reads the tier 3 rate I assume I should ignore the data from that sensor. I hope having two sensors won't be confusing for other people. At least on my configuration I have the 1 day sensor from my meter for the energy integration and I'm using the 1 month sensor from this integration for price so I'll know in a bit over a month how accurate this setup is and I will think about ways of compensating for any error. Thank you for making all these new versions, it seems to all work now.

**Comment by firstof9** [comment]
It's kind of a special sensor, unless they have a tiered rate plan similar to yours the sensor will just state "unknown".

**Comment by coleya** [comment]
I just wanted to update you on the status of the sensor and some other thoughts. It updated to the tier 2 rate at 2pm yesterday when the energy sensor crossed the threshold at 1:13 pm so it seems to work as intended. On the minimum meter charge I found that it is exposed by the api as the mincharge key and the units are provided by the minchargeunits key here is the api response for my updated tariff:
```
{
  "items": [
    {
      "label": "60e4c63a5457a3a91679e0f2",
      "uri": "https://openei.org/apps/IURDB/rate/view/60e4c63a5457a3a91679e0f2",
      "sector": "Residential",
      "energyweekendschedule": [
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        ],
      "enddate": "2021-07-31T00:00:00.000Z",
      "flatdemandunit": "kW",
      "supersedes": "5cbf4ebc5457a3016867107f",
      "demandrateunit": "kW",
      "eiaid": 14328,
      "phasewiring": "Single and 3-Phase",
      "revisions": [
      Jul 6, 2021,
      Jul 6, 2021,
      Sep 13, 2021,
],
      "mincharge": 10,
      "energyratestructure": [
        [
          {
            "max": 6.8,
            "rate": 0.25902,
            "unit": "kWh daily",
          },
          {
            "max": 27.2,
            "rate": 0.32596,
            "unit": "kWh daily",
          },
          {
            "rate": 0.40745,
            "unit": "kWh daily",
          },
        ],
        [
          {
            "max": 8.2,
            "rate": 0.25902,
            "unit": "kWh daily",
          },
          {
            "max": 32.8,
            "rate": 0.32596,
            "unit": "kWh daily",
          },
          {
            "rate": 0.40745,
            "unit": "kWh daily",
          },
        ],
      ],
      "startdate": "2021-03-01T01:00:00.000Z",
      "energyweekdayschedule": [
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        ],
      "fixedchargeunits": "$/month",
      "utility": "Pacific Gas & Electric Co",
      "servicetype": "Bundled",
      "description": "This schedule is applicable to single-phase and polyphase residential service in single-family dwellings and in flats and apartments separately metered by PG&E; to single-phase and polyphase service in common areas in a multifamily complex; and to all single-phase and polyphase farm service on the premises operated by the person whose residence is supplied through the same meter.",
      "name": "E-1 -Residential Service Baseline Region T",
      "source": "http://www.pge.com/tariffs/tm2/pdf/ELEC_SCHEDS_E-1.pdf",
      "approved": true,
      "dgrules": "Net Metering",
      "country": "USA",
      "demandunits": "kW",
      "sourceparent": "https://www.pge.com/tariffs/index.page",
      "minchargeunits": "$/month",
    },
  ],
},
``` 
So the data is there but I'm not sure how to gracefully integrate it into this extension.

**Comment by firstof9** [comment]
Can you open a new issue for a feature request for the mincharge? Thanks.
